### ISSUE TITLE
Add support for NA METAR data

### ISSUE THREAD

**Issue by 57Dojo** [etcher-be/esst#17]
e.g. 
report visibility in statute miles
report wind in knots
report baro pressure in inches of mercury (in/Hg)

thanks!

**Comment by etcher-be** [comment]
Linking to https://github.com/etcher-be/emiz/issues/24

**Comment by etcher-be** [comment]
Can you help me in confirming that the following is accurate:

```
#: Station Location Identifiers - North American formatting
NA_REGIONS = ['C', 'K', 'P', 'T']

#: Station Location Identifiers - International formatting
IN_REGIONS = ['A', 'B', 'D', 'E', 'F', 'G', 'H', 'L', 'N', 'O', 'R', 'S', 'U', 'V', 'W', 'Y', 'Z']
```

Those represents the first letter of the ICAO code for each station depending on their geographical location. I will be using this as a "default" formatter in case a system of units isn't specifically asked for by the user.
