### ISSUE TITLE
Add option to Display METAR

### ISSUE THREAD

**Issue by 57Dojo** [etcher-be/esst#18]
This request is to add the ability retrieve and display the METAR would be for a given airport.  This way, the weather can be examined via the Discord command prior to actually loading it into the mission, in case the mission re-loader decides he doesn't want to use that weather profile (or rather would rather tweak the winds, etc)

**Comment by etcher-be** [comment]
Linking to https://github.com/etcher-be/emiz/issues/24

**Comment by 57Dojo** [comment]
I believe I explained this poorly in the original request.  This is an attempt to make clearer the request: Essentially, the tool has the "-i ICAO" option that fetches real world METAR from given airfield.  However, this function only works when actively loading the real world METAR into a mission during load.  This request is to make the function available to simple fetch and display the real world METAR in the channel, without actively loading it.

**Comment by etcher-be** [comment]
Understood.

Thank you for clarifying !
