### ISSUE TITLE
Error installing ESST

### ISSUE THREAD

**Issue by 57Dojo** [etcher-be/esst#2]
Hey Etcher!  I'm attempting to setup ESST, and during the install, I receive the following errors.  Not sure if they're critical or not.  Please advise!

Thanks in advance,
Dojo

*************************************
**Running setup.py bdist_wheel for ujson ... error**
  Complete output from command C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\clc\\AppData\\Local\\Temp\\pip-install-zpwqr90d\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\clc\AppData\Local\Temp\pip-wheel-im5q_041 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for ujson
  Running setup.py clean for ujson
Failed to build ujson
elib 0.1.57 has requirement certifi==2018.1.18, but you'll have certifi 2018.4.16 which is incompatible.
elib 0.1.57 has requirement pefile==2017.11.5, but you'll have pefile 2018.8.8 which is incompatible.
elib 0.1.57 has requirement pyyaml==3.12, but you'll have pyyaml 3.13 which is incompatible.
emiz 2018.4.2.1 has requirement certifi==2018.1.18, but you'll have certifi 2018.4.16 which is incompatible.
emiz 2018.4.2.1 has requirement natsort==5.2.0, but you'll have natsort 5.3.3 which is incompatible.
emiz 2018.4.2.1 has requirement pefile==2017.11.5, but you'll have pefile 2018.8.8 which is incompatible.
emiz 2018.4.2.1 has requirement pyyaml==3.12, but you'll have pyyaml 3.13 which is incompatible.
Installing collected packages: argh, ujson, emiz, inflect, ESST
  Running setup.py install for ujson ... error
    Complete output from command C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\clc\\AppData\\Local\\Temp\\pip-install-zpwqr90d\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\clc\AppData\Local\Temp\pip-record-32702ckz\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\clc\\AppData\\Local\\Temp\\pip-install-zpwqr90d\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\clc\AppData\Local\Temp\pip-record-32702ckz\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\clc\AppData\Local\Temp\pip-install-zpwqr90d\ujson\
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by 57Dojo** [comment]
I resolved some of the above error by installing Visual Studio.  Wasn't aware that was required.  Now the ESST command activates.  However, it now gives the following error, even though my path appears to include it.  I am showing the current path below for your reference, as well as the error:

current path: 
```
C:\>PATH
PATH=C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\Miniconda3\Scripts\;C:\Users\clc\AppData\Local\Microsoft\WindowsApps
```


and here is the error:

```
(ESST) C:\>esst
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\esst.exe\__main__.py", line 5, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\esst\__main__.py", line 9, in <module>
    import elib
  File "c:\programdata\miniconda3\lib\site-packages\elib\__init__.py", line 9, in <module>
    from . import config, console, custom_logging, custom_random, downloader, exe_version, hash_, paste, path, pretty, \
  File "c:\programdata\miniconda3\lib\site-packages\elib\repo.py", line 9, in <module>
    import git
  File "c:\programdata\miniconda3\lib\site-packages\git\__init__.py", line 82, in <module>
    refresh()
  File "c:\programdata\miniconda3\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\programdata\miniconda3\lib\site-packages\git\cmd.py", line 293, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by 57Dojo** [comment]
I have progressed this further... now when attempting to run ESST, I get the following:

C:\Utils\ESST>pipenv run esst
00000362 ms     INFO ESST.esst.utils.sentry initializing Sentry
00000365 ms     INFO ESST.esst.utils.sentry Sentry is ready
00000375 ms    DEBUG ESST.esst.utils.sentry registering context with Sentry: App context
00000375 ms    DEBUG ESST.esst.utils.sentry registering context with Sentry: Config
00000829 ms    DEBUG ESST.esst.discord_bot.commands Discord can start
00000841 ms    DEBUG ESST starting ESST 2018.6.15.2
00000841 ms    DEBUG ESST.esst.core.fs_paths init
00000842 ms    DEBUG ESST.esst.core.fs_paths Saved Games path found in Config
00000843 ms    DEBUG ESST.esst.core.fs_paths Saved Games path: C:\Users\clc\Saved Games
00000843 ms    DEBUG ESST.esst.core.fs_paths DCS path: C:\Program Files\Eagle Dynamics\DCS World
00000844 ms    DEBUG ESST.esst.core.fs_paths DCS exe: C:\Program Files\Eagle Dynamics\DCS World\bin\dcs.exe
00000850 ms    DEBUG ESST.esst.core.fs_paths Saved Games variant: C:\Users\clc\Saved Games\DCS
00000885 ms    DEBUG ESST.esst.core.fs_paths DCS autoexec: C:\Users\clc\Saved Games\DCS\Config\autoexec.cfg
00000922 ms    DEBUG ESST.esst.core.fs_paths Mission Editor lua file: C:\Program Files\Eagle Dynamics\DCS World\MissionEditor\MissionEditor.lua
00000945 ms    DEBUG ESST.esst.core.fs_paths DCS hook: C:\Users\clc\Saved Games\DCS\Scripts\Hooks\esst.lua
00000947 ms    DEBUG ESST.esst.core.fs_paths DCS mission folder: C:\Users\clc\Saved Games\DCS\Missions\ESST
00000956 ms    DEBUG ESST.esst.core.fs_paths DCS server settings: C:\Users\clc\Saved Games\DCS\Config\serverSettings.lua
00000958 ms    DEBUG ESST.esst.core.fs_paths DCS log folder: C:\Users\clc\Saved Games\DCS\logs
00000959 ms    DEBUG ESST.esst.core.fs_paths FS paths initialised
00000959 ms    DEBUG ESST.esst.utils.remove_old_files no folder to clean
00000960 ms    DEBUG ESST.esst.atis._univers_radio._ur_install_dir discovering UR install path
00000960 ms    DEBUG ESST.esst.atis._univers_radio._ur_install_dir no UR install path in Config, looking it up
00000961 ms    DEBUG ESST.esst.atis._univers_radio._ur_install_dir searching for base "Saved Games" folder
00000962 ms    DEBUG ESST.esst.atis._univers_radio._ur_install_dir using Saved Games path: None
00000963 ms    DEBUG ESST.esst.utils checking for backup of C:\Users\clc\Saved Games\UniversRadio\VoiceService.dat
00000964 ms    DEBUG ESST.esst.utils original does no exist, skipping backup: C:\Users\clc\Saved Games\UniversRadio\VoiceService.dat
00000964 ms    DEBUG ESST.esst.utils.sentry registering context with Sentry: ATIS
00000965 ms    DEBUG ESST.esst.utils.sentry registering context with Sentry: UR
00001147 ms    DEBUG ESST.esst.discord_bot.discord_bot starting Discord bot
00001147 ms    DEBUG ESST.esst.discord_bot.logging_handler registering Discord logging handler
00001158 ms    DEBUG ESST.esst.listener.listener starting socket thread
00001159 ms    DEBUG ESST.esst.wan starting connection monitoring loop
00001297 ms    DEBUG ESST.esst.discord_bot.discord_bot starting Discord client
00003329 ms    DEBUG ESST.esst.server.server end of Server computer loop
00003330 ms    DEBUG ESST.esst.utils.sentry capturing exception
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Miniconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\clc\.virtualenvs\ESST-X3AZBxmP\Scripts\esst.exe\__main__.py", line 9, in <module>
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\click\core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\esst\__main__.py", line 147, in main
    loop.run_until_complete(futures)
  File "C:\ProgramData\Miniconda3\Lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\esst\dcs\dcs.py", line 319, in run
    if not await self._get_dcs_version_from_executable():
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\esst\dcs\dcs.py", line 82, in _get_dcs_version_from_executable
    core.Status.dcs_version = utils.Win32FileInfo(str(core.FS.dcs_exe)).file_version
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\esst\utils\__init__.py", line 149, in __init__
    self.__read_props()
  File "c:\users\clc\.virtualenvs\esst-x3azbxmp\lib\site-packages\esst\utils\__init__.py", line 232, in __read_props
    pvms = pe_file.VS_FIXEDFILEINFO.ProductVersionMS  # pylint: disable=no-member
AttributeError: 'list' object has no attribute 'ProductVersionMS'

**Comment by etcher-be** [comment]
Since the latest few release, the preferred method to install ESST is using the provided executable.

In a future release, an automated updater will be integrated to alleviate the issue of having to constantly have to manually replace the executable.

This system will also allow for testing versions & feature branches build artifacts to be painlessly passed around.

I'm closing the issue for now.
